---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-apacheds_installation.yml'
  ansible.builtin.import_playbook: playbook-apacheds_installation.yml
