---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-apacheds_installation.yml'
  ansible.builtin.import_playbook: playbook-apacheds_installation.yml

- name: 'Run playbook-postgresql_installation.yml'
  ansible.builtin.import_playbook: playbook-postgresql_installation.yml

- name: 'Run playbook-zitadel_installation.yml'
  ansible.builtin.import_playbook: playbook-zitadel_installation.yml
